### ISSUE TITLE
Package categories

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/soilmoisturetools#48]
We are trying to categorize the packages in USGS-R. For more details, see:
https://owi.usgs.gov/R/packages.html

I'd recommend this package as "Support". When you decide what you think this package could be, you could add a badge to your readme:

[![status](https://img.shields.io/badge/USGS-Support-yellow.svg)](https://owi.usgs.gov/R/packages.html#support)

If you wanted to include a link or note in your package startup message, we added that to some packages too. For example:

https://github.com/USGS-R/smwrQW/blob/master/R/smwrQW-package.R#L29

**Comment by mhines-usgs** [comment]
Emailing this inquiry to Jessica Lucido, the project manager for this package.

**Comment by mhines-usgs** [comment]
https://github.com/USGS-R/soilmoisturetools/pull/49
